site_name: Intelligent App Workshop with Project Miyagi and Semantic Kernel
site_description: Complimentary workshop to Project Miyagi to demonstrate the potential of integrating SoTA foundation models in user experiences and backend workflows. Orchestrated by Semantic Kernel and built on Azure primitives.
site_author: Azure App Innovation GBB, Microsoft
nav:
  - Home: index.md
  - Intro: wksp/00-intro/index.md
  - Agenda & Outcomes: wksp/00-intro/agenda-and-outcomes.md
  - Miyagi Architecture Overview: wksp/00-intro/architecture-overview.md
  - Sample Walkthroughs for inspiration: wksp/00-intro/samples-walk-through.md
  - Semantic Kernel overview: wksp/00-intro/semantic-kernel-overview.md
  - Pre-requisites: wksp/00-intro/pre-reqs.md
  - Module 1 - Design thinking session: 
    - wksp/01-design-thinking/index.md
    - HEART Framework: wksp/01-design-thinking/heart-framework.md
    - Design Thinking Canvas: wksp/01-design-thinking/design-thinking-canvas.md
  - Module 2 - Fork and Get Hands-on: wksp/02-fork-and-get-hands-on/index.md
  - Module 3 - Inner-loop: wksp/03-inner-loop/index.md
  - Module 4 - Basics of Semantic Kernel: wksp/04-Semantic-Kernel-Basics/index.md
  - Module 5 - Use cases deep-dive with Miyagi and Reddog: 
    - wksp/05-use-cases/index.md
    - Synthesis: wksp/05-use-cases/synthesis.md
    - Generation (Text, Images): wksp/05-use-cases/generation.md
    - Conversation: wksp/05-use-cases/generation.md
    - Summarization: wksp/05-use-cases/generation.md
    - Classification: wksp/05-use-cases/generation.md
    - Translation: wksp/05-use-cases/generation.md
    - Speech-to-text: wksp/05-use-cases/generation.md
    - Semantic Search: wksp/05-use-cases/generation.md
    - Anomaly Detection: wksp/05-use-cases/generation.md
    - Plugins: wksp/05-use-cases/generation.md
  - Post-workshop:
    - Feedback: wksp/other/feedback.md
  
theme:
  name: material
  custom_dir: docs/assets/overrides
  font:
    text: Inter
  palette:
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  features:
    - header.autohide
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - toc.follow
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.ico

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: '.'
      check_paths: true
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - md_in_html

copyright: Copyright &copy; 2023 Azure App Innovation GBB, Microsoft

plugins:
  - git-revision-date
  - search
  - macros
  - glightbox
  - open-in-new-tab

extra:
  analytics:
    provider: google
    property: G-W6SKQMVB9X
  generator: false
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >-
          Thanks for your feedback! - App Innovation GBB
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: >- 
          Thanks for your feedback! Help App Innovation GBB team improve this page by
          using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Azure/intelligent-app-workshop

extra_css:
  - assets/stylesheets/extra.css

repo_url: https://github.com/Azure/intelligent-app-workshop
edit_uri: edit/main/docs

